#2.列表
squres=[1,2,3,4,5]
print(squres[0])#下标是从零开始
newSqures=squres+[2,78,3,6]
print(newSqures)
#与字符串不同的是，列表可以更改列表项的值
a=3**5
squres[2]=a
print(squres)
#append()方法可以将元素添加在列表最后一项
cu=["p","y","t","h","o","n"]
cube1=["p""y""t""h""o""n"]#当每个列表中字符串之间不加逗号的时候，默认为拼接在一起的一个单词，一个引号把所有内容放在里面
print(cu)
print(cube1)
cu.append("myLove")
print(cu)
cu.clear()
cu1=["this","is","a","good","day"]
print(cu1)
cu1.copy()#将原本内容复制一遍
print(cu1)
cube=[9,9,75,6,4]
print(cube)
cube.pop()#删除最后一个元素，与append相反
print(cube)
print(cube[2:4])#在python中，截取中间为冒号：
print(len(cube))#显示其长度
#拼接的另一种方法：
a=['a','b','c']
n=[1,2,3]
x=[a,n]
print(x)
print(x[0])
print(x[0][1])#表示输出数组的下标为0元素中下标为1的元素